# theme = 'onelight'
# theme = 'rose_pine_moon'
# theme = 'base16_transparent'
theme = 'gruber-darker'

[editor]
line-number = 'relative'
popup-border = 'all'

[editor.cursor-shape]
insert = 'bar'
normal = 'block'
select = 'underline'

[editor.file-picker]
hidden = false

[editor.whitespace]
render = 'all'

[editor.indent-guides]
render = true
skip-levels = 1


[keys.normal]
ret = 'command_mode'
