# theme = 'base16_transparent'
# theme = 'gruber-darker'
# theme = 'bogster'
# theme = 'tokyonight_day'
# theme = 'tokyonight_moon'
# theme = 'iroaseta'
theme = 'amberwood'
# theme = 'ayu_dark'
# theme = 'everforest_light'
# theme = 'onelight'
# theme = 'acme'
# theme = 'spacebones_light'

[editor]
true-color = true
line-number = 'relative'
popup-border = 'all'
end-of-line-diagnostics = "hint"
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
mouse = false

[editor.lsp]
display-inlay-hints = true
auto-signature-help = true
display-progress-messages = true

[editor.cursor-shape]
insert = 'block'
normal = 'block'
select = 'underline'

[editor.file-picker]
hidden = false

[editor.whitespace]
render = 'all'

[editor.indent-guides]
render = true
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"

[keys.normal]
ret = 'command_mode'
