[[language]]
name = "tsx"
auto-format = true
formatter = { command = "eslint_d" , args = ["--stdin", "--fix-to-stdout", "--stdin-filename", "src/index.tsx"] }
# formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "eslint_d" , args = ["--stdin", "--fix-to-stdout", "--stdin-filename", "src/index.tsx"] }
# formatter = { command = "prettier", args = ["--parser", "typescript"] }

# [language-server.efm-lsp-prettier]
# command = "efm-langserver"

# [language-server.efm-lsp-prettier.config]
# documentFormatting = true
# languages = { typescript = [{ formatCommand = "prettier --stdin-filepath ${INPUT}", formatStdin = true }]}

