evaluate-commands %sh{
    plugins="$kak_config/bundle"
    mkdir -p "$plugins"
    [ ! -e "$plugins/kak-bundle" ] && \
        git clone -q https://codeberg.org/jdugan6240/kak-bundle "$plugins/kak-bundle"
    printf "%s\n" "source '$plugins/kak-bundle/rc/kak-bundle.kak'"
}
bundle-noload kak-bundle https://codeberg.org/jdugan6240/kak-bundle

bundle kakoune-lsp https://github.com/kakoune-lsp/kakoune-lsp %{
    eval %sh{kak-lsp}
    lsp-enable

    set-option global modelinefmt "%opt{lsp_modeline} %opt{modelinefmt}"

    map global user l ':enter-user-mode lsp<ret>' -docstring 'LSP mode'
    map global goto d '<esc>:lsp-definition<ret>'      -docstring 'LSP definition'
    map global goto r '<esc>:lsp-references<ret>'       -docstring 'LSP references'
    map global goto y '<esc>:lsp-type-definition<ret>'  -docstring 'LSP type definition'
}
bundle-install-hook kakoune-lsp %{
    cargo install --locked --force --path .
}
bundle-cleaner kakoune-lsp %{
    rm -f ~/.cargo/bin/kak-lsp
}

bundle kak-tree-sitter https://git.sr.ht/~hadronized/kak-tree-sitter %{
    eval %sh{
        kak-tree-sitter --init "${kak_session}" --kakoune --daemonize --server --with-highlighting
    }
}
bundle-install-hook kak-tree-sitter %{
    cargo install --locked --force --path kak-tree-sitter
    cargo install --locked --force --path ktsctl
}

bundle luar "https://github.com/gustavo-hms/luar" %{
    require-module luar
}
bundle peneira "https://github.com/gustavo-hms/peneira" %{
    require-module peneira

    define-command -override peneira-buffers -docstring 'peneira-buffers: переключить буфер' %{
        peneira 'buffers: ' %{ eval "printf '%s\n' $kak_quoted_buflist" } %{
            buffer %arg{1}
        }
    }

    map global normal <c-p> ': peneira-files<ret>'   -docstring 'найти файл'
    map global normal <c-b> ': peneira-buffers<ret>' -docstring 'переключить буфер'

    map global user f ': peneira-files<ret>'   -docstring 'найти файл (<c-p>)'
    map global user b ': peneira-buffers<ret>' -docstring 'переключить буфер (<c-b>)'
    map global user / ': peneira-lines<ret>'   -docstring 'поиск по строкам буфера'
}

bundle auto-pairs "alexherbo2/auto-pairs.kak" %{
    require-module auto-pairs
    hook global WinCreate .* auto-pairs-enable
}

bundle mru-files https://gitlab.com/kstr0k/mru-files.kak %{
    set-option global mru_files_max 50
    require-module mru-files

    map global user r ': mru-files-list<ret>' -docstring 'недавние файлы…'
    map global goto <a-f> '<esc>: mru-files '        -docstring 'mru-files'
    map global goto <a-F> '<esc>: mru-files-related<ret>' -docstring 'mru-files-related'
}

bundle kakoune-snippets "occivink/kakoune-snippets" %{
    require-module snippets
}
bundle kakoune-snippet-collection "andreyorst/kakoune-snippet-collection" %{
    set-option -add global snippets_directories \
        "%val{config}/bundle/kakoune-snippet-collection/snippets"
}

set-option global autoinfo command|onkey

map global user c ': comment-line<ret>'    -docstring 'переключить коммент'
map global user n ': buffer-next<ret>'     -docstring 'следующий буфер'
map global user N ': buffer-previous<ret>' -docstring 'предыдущий буфер'

bundle-theme kakoune-themes "anhsirk0/kakoune-themes"
colorscheme default
